### ISSUE TITLE
项目使用css module设置背景图url编译后路径有误

### ISSUE THREAD

**Issue by GaryHjy** [efoxTeam/emp#89]
## 问题
css module设置背景图编译后路径有误

## 描述
 使用css module打包后出现图片加载失败

```css
.hello-word {
  height: 800px;
  background: url(~@/assets/images/banner.jpg) no-repeat;
  background-size: 100%;
  color: #fff;
}
```

## 复现demo地址

https://github.com/GaryHjy/emp-project
